# This is a basic workflow to help you get started with Actions

name: Update Dependencies

on:
  schedule:
    - cron: '00 08 * * 0'
jobs:
  version-update:
    runs-on: macos-latest
    environment: Dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Perform dependencies resolution and update
        run: ./gradlew versionCatalogUpdate
      - name: Build and Test
        run: ./gradlew clean build test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
      # Runs a set of commands using the runners shell
      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update dependencies"
          body: " Dependencies update.
            Check the Version Catalog to see which dependencies need an update.
        "
          commit-message: "Update version catalog"
